### ISSUE TITLE
Problem with UUIDs?

### ISSUE THREAD

**Issue by thiagomajesk** [goodpixel/chunkr#3]
Hi! Was testing  this lib today (nice work btw 😉), and stumbled upon this wild error message:

```
Postgrex expected a binary of 16 bytes, got "333d277e-bc1d-4ee6-b92d-ee71110917b1". Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly.
```

This only happens if I try to use my ids (uuids) in the paginate strategy (works fine without the their line):

```elixir
paginate_by :merchant do
  sort(:asc, as(:merchant).name)
  sort(:desc, as(:merchant).id)
  sort(:desc, as(:merchant).inserted_at)
end
```

This is the usual definition my schemas use:

```elixir
defmodule MyApp.Schema do
  defmacro __using__(_) do
    quote do
      use Ecto.Schema
      @primary_key {:id, :binary_id, autogenerate: true}
      @foreign_key_type :binary_id
    end
  end
end
```

Is this a bug in the lib or a hint for an underlying problem?

**Comment by bencoppock** [comment]
Hi @thiagomajesk, thanks for checking out Chunkr!

I also use UUIDs. This error happens in cases where Ecto doesn't know to cast a value as a UUID. And I _believe_ it happens here specifically because the cursor has a UUID as part of it, but Ecto has no idea that the value in question is a UUID (I guess because the cursor itself doesn't have a schema to tell Ecto that?). 

Whatever the case, I've handled this by allowing you to pass an extra `type: :binary_id` option to your `sort` clause. See https://hexdocs.pm/chunkr/Chunkr.PaginationPlanner.html for an example. 

As a side note, I see that you're using merchant `inserted_at` as your ultimate tie breaker. Unless you _know_ that this timestamp is always unique, you won't want to use it that way. You want to make sure your final tie breaker is always unique—otherwise you'll get unpredictable results when paginating. 

Moreover, since merchant ID is a UUID, I'm assuming you have a uniqueness constraint on it in the DB, and therefore it would in fact make an excellent final tie breaker. In fact, there's no sense in making the sort logic more complex with a third sort since the second sort will always be deterministic and the third sort is unneeded in this case. 

However, I do realize you're just focused on trying to get UUIDs working right now so you may already be aware of all of that. 😄

Let me know if this gets you up and running!

**Comment by thiagomajesk** [comment]
Hi again @bencoppock! Sorry if I mislead you, I didn't mean that I'd have to copy the whole schema information over, I meant specifically for the fields you'd want pagination strategies for.

> Do you have other cases in mind besides UUIDs where you'd need to explicitly provide Chunkr with a type? I'm sure there are some, just not sure how common they'd be…

See if this makes sense to you... I'm working on a project right now (not the one I was testing Chunkr with), where we do LIMIT-based pagination at already some cost. We have two or three schemas that are backed by the same table/ view, but each one of them requires a different type of pagination strategy to be executed (imagine a big denormalized table).  This means that I have to keep my schema's field types in sync, right!? 

```elixir
paginate_by :foo do
  sort(:asc, as(:foo).name)
  sort(:desc, as(:foo).id), type: :uuid
end

paginate_by :bar do
  sort(:asc, as(:bar).geo), type: Geo.PostGIS.Geometry
  sort(:desc, as(:bar).id), type: :uuid
end

paginate_by :baz do
  sort(:asc, as(:bar).tags), type: MyCustomTagsType
  sort(:desc, as(:bar).id), type: :uuid
end
```

> I like your idea of using the schema module to automatically figure out types. However, I think it would make the implementation a bit more complex. But more of a concern is that it would tightly couple pagination strategies to Ecto schemas.

Aren't the lib already ["hard-coupled"](https://github.com/elixir-ecto/ecto_sql/blob/master/mix.exs#L80) because of the explicit `ecto` dependency from `ecto_sql`? Although you are right to consider how much of the API you want to expose given how complex it would be (I didn't look at the codebase yet tbh).

> I'd have to think about it more, but I believe there's benefit in keeping pagination strategies fully decoupled from Ecto schemas. E.g. you don't need to be using Ecto schemas to use Chunkr, you can use dynamically-generated fields that don't actually exist in your tables, etc. The pagination strategy itself can accept any query so long as the query supplies all the referenced bindings.

This would be in addition to the current approach, not to replace it though. I could be wrong, however, I'd still argue that most of the common use-cases would still be around Ecto schemas, don't you think!? Even schemas and embeds are just special structs with some type hints fields in them, right? Take the [`change/2`](https://hexdocs.pm/ecto/Ecto.Changeset.html#change/2) function from `Ecto.Changeset` as an example, you can pass a changeset a struct or even a list of types, so it's really flexible.

**PS.:** Since we are branching the discussion and you have already answered it, I'll close the issue to make your work a bit easier 😅 . Thanks for replying to my question, if you are interested we could try to explore a little further if this would really be useful or not (it seems that the project does not have a Discussion tab).
